asset_root: public
asset_path: "/assets"

load_path:
  - app/assets
  - lib/assets
  - vendor/assets
  - public

source_files:
  js:
    - js/base.js
    - js/analize.js
    - js/documents.js
    - js/person.js
  css:
    - css/base.css

js_compressor_options:
  munge: true

css_compressor_options:
